import{i as a,S as d}from"./assets/vendor-0fc460d7.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const u="44648929-0a3ca09e28beb33e491a22410";function f(e){const n=`https://pixabay.com/api/?key=${u}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(n).then(r=>{if(!r.ok)throw new Error(`HTTP error! Status: ${r.status}`);return r.json()}).then(r=>r.hits.map(s=>({webformatURL:s.webformatURL,largeImageURL:s.largeImageURL,tags:s.tags,likes:s.likes,views:s.views,comments:s.comments,downloads:s.downloads}))).catch(r=>{throw console.error("Error fetching images:",r),r})}function m(e){return`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" />
      <div class="info">
        <p><strong>Likes:</strong> ${e.likes}</p>
        <p><strong>Views:</strong> ${e.views}</p>
        <p><strong>Comments:</strong> ${e.comments}</p>
        <p><strong>Downloads:</strong> ${e.downloads}</p>
      </div>
    </a>
  `}function g(e){const n=document.querySelector(".gallery[data-gallery]");n.innerHTML=e.map(m).join("")}function h(e){e.innerHTML=""}const p=document.getElementById("search-form"),y=document.getElementById("search-input"),c=document.getElementById("gallery"),l=document.getElementById("loading-indicator");p.addEventListener("submit",e=>{e.preventDefault();const n=y.value.trim();if(n===""){a.error({message:"Пожалуйста, введите ключевое слово для поиска."});return}h(c),L(),f(n).then(r=>{r.length===0?a.info({message:"Sorry, there are no images matching your search query. Please try again!"}):(g(c),I())}).catch(r=>{console.error("Ошибка при загрузке изображений:",r),a.error({message:"Не удалось загрузить изображения. Пожалуйста, попробуйте позже."})}).finally(()=>{w()})});function L(){l.classList.remove("hidden")}function w(){l.classList.add("hidden")}function I(){new d(".gallery a",{}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
