import{i,S as d}from"./assets/vendor-0fc460d7.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const u="44648929-0a3ca09e28beb33e491a22410";function f(e){const n=`https://pixabay.com/api/?key=${u}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(n).then(t=>{if(!t.ok)throw new Error(`HTTP error! Status: ${t.status}`);return t.json()}).then(t=>t.hits.map(s=>({webformatURL:s.webformatURL,largeImageURL:s.largeImageURL,tags:s.tags,likes:s.likes,views:s.views,comments:s.comments,downloads:s.downloads}))).catch(t=>{throw console.error("Error fetching images:",t),t})}function m(e){return`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" />
      <div class="info">
        <p><strong>Likes:</strong> ${e.likes}</p>
        <p><strong>Views:</strong> ${e.views}</p>
        <p><strong>Comments:</strong> ${e.comments}</p>
        <p><strong>Downloads:</strong> ${e.downloads}</p>
      </div>
    </a>
  `}function g(e){const n=document.getElementById("gallery");n.innerHTML=e.map(m).join("")}function h(e){e.innerHTML=""}const p=document.getElementById("search-form"),c=document.getElementById("search-input"),y=document.getElementById("gallery"),l=document.querySelector(".loader");p.addEventListener("submit",e=>{e.preventDefault();const n=c.value.trim();if(n===""){i.error({message:"Please enter a search keyword."});return}h(y),L(),f(n).then(t=>{t.length===0?i.info({message:"Sorry, no images matching your search query were found. Please try again!"}):(g(t),I(),c.value="")}).catch(t=>{console.error("Error loading images:",t),i.error({message:"Failed to load images. Please try again later."})}).finally(()=>{w()})});function L(){l.classList.remove("hidden")}function w(){l.classList.add("hidden")}function I(){new d(".gallery a",{}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
